export enum ComicsStatusEnum {
  UNAVAILABLE = 'UNAVAILABLE',
  AVAILABLE = 'AVAILABLE',
  AUCTION = 'AUCTION',
  EXCHANGE = 'EXCHANGE',
  EXCHANGE_OFFER = 'EXCHANGE_OFFER',
  SOLD = 'SOLD',
  REMOVED = 'REMOVED',
}
