export enum OrderDeliveryStatusEnum {
  READY_TO_PICK = 'ready_to_pick',
  PICKING = 'picking',
  CANCEL = 'cancel',
  MONEY_COLLECT_PICKING = 'money_collect_picking',
  PICKED = 'picked',
  STORING = 'storing',
  TRANSPORTING = 'transporting',
  SORTING = 'sorting',
  DELIVERING = 'delivering',
  MONEY_COLLECT_DELIVERING = 'money_collect_delivering',
  DELIVERED = 'delivered',
  DELIVERY_FAIL = 'delivery_fail',
  WAITING_TO_RETURN = 'waiting_to_return',
  RETURN = 'return',
  RETURN_TRANSPORTING = 'return_transporting',
  RETURN_SORTING = 'return_sorting',
  RETURNING = 'returning',
  RETURN_FAIL = 'return_fail',
  RETURNED = 'returned',
}
