export enum ExchangeStatusEnum {
  PENDING = 'PENDING',
  DEALING = 'DEALING',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
}
