export enum StatusQueryEnum {
  ALL = 'ALL',
  PENDING_REQUEST = 'PENDING_REQUEST',
  SENT_REQUEST = 'SENT_REQUEST',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_DELIVERY = 'IN_DELIVERY',
  FINISHED_DELIVERY = 'FINISHED_DELIVERY',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
}
